
name: First workflow

# ¿When starting? -> Triggers
on: [push]

jobs: 

    build: # name of the event
        runs-on: ubuntu-latest # where s.o

        steps: 
            - uses: actions/checkout@v3

            - name: Hello Friends
              run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"